### ISSUE TITLE
Opinion about local vs global CSS

### ISSUE THREAD

**Issue by basham** [basham/cycle-demo#2]
From @ivan-kleshnin, #1:

> Do you have an established opinion about local vs global CSS?

**Comment by basham** [comment]
For over a year, I've been a strong advocate for the [BEM methodology](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/), eventually settling on my own variation which has been quite successful for a number of personal and professional projects. I've wrote and presented about this technique a number of times:
- [_Kuali Student CSS Best Practices_](https://gist.github.com/basham/877db54fffb08e47bd39), Aug 2014
- [_Architecting CSS_](https://speakerdeck.com/basham/architecting-css), Aug 2014

I've been impressed by other approaches, such as [AMCSS](https://amcss.github.io/), which attempts to resolve some of the rigor needed to successfully implement BEM. But there are some performance concerns with this technique, since it avoids class names, which are efficiently indexed by browsers.

However, I've been mostly converted to CSS Modules upon initially reading about them ([_The End of Global CSS_](https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284), May 2015). Its easy integration with [Webpack](http://webpack.github.io/) combined with Webpack's hot reloading capabilities converted me from a mostly [gulp](http://gulpjs.com/)/[Browserify](http://browserify.org/) build environment.

I've come to appreciate the advantage of CSS modules even more, upon reading how it practically can replace BEM ([_CSS Modules_](http://glenmaddern.com/articles/css-modules), Aug 2015).

I will probably still use BEM for projects which are inherently less app-like. For example, I'm not quite sure how to take advantage of CSS modules when writing, say, a static site, like my [portfolio](https://github.com/basham/v4.bash.am). And I'm sure it would be even more complicated for dynamic sites.

Returning to your original question, @ivan-kleshnin, local CSS is a very good evolution for how we approach authoring components and isolating their effects. It gives us a great ability to avoid the headaches of global CSS, without heading to the extreme of just inline styling everything (see [`Radium`](http://projects.formidablelabs.com/radium/)), which has the consequence of JavaScript needing to reimplement simple things, such as pseudo elements and media queries. Local CSS is the best current approach to sustain us until [scoped CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Ascope) is finalized and adopted by browser implementors.

**Comment by ivan-kleshnin** [comment]
Great, thank you! I think I'm going in the same direction. Never heard of scoped CSS. Cool input.
I'm glad that I asked you ;)

**Comment by basham** [comment]
Please reach out if you have more questions. Glad to share.
